site_name: GooberDocs
site_url: "https://docs.goobercorp.com"
site_description: "Official Documentation of GooberCorp projects"
repo_url: https://github.com/Goober-Corp/GooberDocs
repo_name: Goober-Corp/GooberDocs

theme:
  name: material